clc;
clear;
load E:\SemanticSegmentation_Scale\CPL\GTruth_Revolve_1433.mat;
load E:\SemanticSegmentation_Scale\Results\MuliImageSS_ResNet50_SeriesClass_ResAttention\trainedNet_resnet50_5.mat;

imageDir = 'E:\SemanticSegmentation_Scale\NET_Muli_CPL_XPL_All\Revolve_Imds_Test\';
imds = imageDatastore(imageDir,...
    'IncludeSubfolders',false,...
    'FileExtensions','.mat',...
    'LabelSource','foldernames',...
    ReadFcn = @matRead6Channels);% 训练图像'ReadFcn' 'matRead6Channels',...
classNames = ["Quartz","Feldspar","Debris","BlackMica","Muscovite","RedCasting","BuleCasting","magnetite","Chert","siderite","Scale100","Scale200","Scale50","Glauconite"];
pxds = pixelLabelDatastore(GTruth);% 图像标签
pxdsResults = semanticseg(imds,net, ...
    'MiniBatchSize',1, ...
    'WriteLocation',tempdir, ...
    'Verbose',false);
metrics = evaluateSemanticSegmentation(pxdsResults,pxds,'Verbose',false);
metrics.DataSetMetrics
metrics.ClassMetrics