% 语义分割
clear;
clc;
load E:\TYUT\岩石薄片识别\盒8\SemanticSegmentation_Scale\CPL\GTruth_Revolve_12903.mat;

imageDir = 'E:\TYUT\岩石薄片识别\盒8\SemanticSegmentation_Scale\NET_Muli_CPL_XPL_All\Revolve_Imds_Train\';

imds = imageDatastore(imageDir,...
    'IncludeSubfolders',false,...
    'FileExtensions','.mat',...
    'LabelSource','foldernames',...
    ReadFcn = @matRead6Channels);% 训练图像'ReadFcn' 'matRead6Channels',...
classNames = ["Quartz","Feldspar","Debris","BlackMica","Muscovite","RedCasting","BuleCasting","magnetite","Chert","siderite","Scale100","Scale200","Scale50","Glauconite"];
pxds = pixelLabelDatastore(GTruth);% 图像标签

imageSize = [224,224];
numClasses = numel(classNames);% 返回classNames中元素个数

%手动插入网络，因为网络是多通道图片为基础

% lgraph = deeplabv3plusLayers(imageSize,numClasses,'resnet50');% 使用labv3架构

pximds = pixelLabelImageDatastore(imds,pxds,'OutputSize',[224,224],...
    'ColorPreprocessing','gray2rgb');

opts = trainingOptions('sgdm',...
    "ExecutionEnvironment","gpu",...
    "InitialLearnRate",0.001,...
    'MiniBatchSize',32,...
    "Plots","training-progress",...
    'MaxEpochs',30);
[net,info] = trainNetwork(pximds,lgraph,opts);